CREATE TABLE IF NOT EXISTS job_details (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id INT UNSIGNED NOT NULL,
    order_item_id INT UNSIGNED DEFAULT NULL,
    source_sheet_row INT UNSIGNED DEFAULT NULL,
    service_type VARCHAR(100) DEFAULT NULL,
    description VARCHAR(255) NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    selling_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    sales_total DECIMAL(12,2) AS (ROUND(quantity * selling_price, 2)) STORED,
    labor_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    raw_material_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    consumable_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    other_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_job_cost DECIMAL(12,2) AS (labor_cost + raw_material_cost + consumable_cost + other_cost) STORED,
    gross_profit DECIMAL(12,2) AS (ROUND((quantity * selling_price) - labor_cost - raw_material_cost - consumable_cost - other_cost, 2)) STORED,
    assigned_staff_name VARCHAR(255) DEFAULT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    findings_notes TEXT DEFAULT NULL,
    completion_date DATE DEFAULT NULL,
    customer_approved_price DECIMAL(12,2) DEFAULT NULL,
    created_by INT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_job_details_order_item (order_item_id),
    UNIQUE KEY uq_job_details_source_row (job_id, source_sheet_row),
    KEY idx_job_details_job (job_id),
    KEY idx_job_details_status (status),
    CONSTRAINT fk_job_details_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_details_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE SET NULL,
    CONSTRAINT fk_job_details_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;