INSERT INTO permissions (module, action, description)
SELECT catalog.module, catalog.action, catalog.description
FROM (
    SELECT 'dashboard' AS module, 'view' AS action, 'View dashboard' AS description
    UNION ALL SELECT 'customers', 'view', 'View customers'
    UNION ALL SELECT 'customers', 'create', 'Create customers'
    UNION ALL SELECT 'customers', 'edit', 'Edit customers'
    UNION ALL SELECT 'customers', 'delete', 'Delete customers'
    UNION ALL SELECT 'vehicles', 'view', 'View vehicles'
    UNION ALL SELECT 'vehicles', 'create', 'Create vehicles'
    UNION ALL SELECT 'vehicles', 'edit', 'Edit vehicles'
    UNION ALL SELECT 'vehicles', 'delete', 'Delete vehicles'
    UNION ALL SELECT 'inquiries', 'view', 'View inquiries'
    UNION ALL SELECT 'inquiries', 'create', 'Create inquiries'
    UNION ALL SELECT 'inquiries', 'edit', 'Edit inquiries'
    UNION ALL SELECT 'inquiries', 'delete', 'Delete inquiries'
    UNION ALL SELECT 'quotations', 'view', 'View quotations'
    UNION ALL SELECT 'quotations', 'create', 'Create quotations'
    UNION ALL SELECT 'quotations', 'edit', 'Edit quotations'
    UNION ALL SELECT 'quotations', 'delete', 'Delete quotations'
    UNION ALL SELECT 'quotations', 'approve', 'Approve quotations'
    UNION ALL SELECT 'orders', 'view', 'View orders'
    UNION ALL SELECT 'orders', 'create', 'Create orders'
    UNION ALL SELECT 'orders', 'edit', 'Edit orders'
    UNION ALL SELECT 'orders', 'delete', 'Delete orders'
    UNION ALL SELECT 'orders', 'approve', 'Approve orders'
    UNION ALL SELECT 'jobs', 'view', 'View jobs'
    UNION ALL SELECT 'jobs', 'create', 'Create jobs'
    UNION ALL SELECT 'jobs', 'edit', 'Edit jobs and job details'
    UNION ALL SELECT 'jobs', 'delete', 'Delete jobs'
    UNION ALL SELECT 'jobs', 'approve', 'Approve jobs'
    UNION ALL SELECT 'inventory', 'view', 'View inventory'
    UNION ALL SELECT 'inventory', 'create', 'Create inventory items'
    UNION ALL SELECT 'inventory', 'edit', 'Edit inventory items'
    UNION ALL SELECT 'inventory', 'delete', 'Delete inventory items'
    UNION ALL SELECT 'stock_movement', 'view', 'View stock movements'
    UNION ALL SELECT 'stock_movement', 'create', 'Record stock movements'
    UNION ALL SELECT 'inventory_requests', 'view', 'View inventory requests'
    UNION ALL SELECT 'inventory_requests', 'create', 'Create inventory requests'
    UNION ALL SELECT 'inventory_requests', 'edit', 'Edit inventory requests'
    UNION ALL SELECT 'inventory_requests', 'approve', 'Approve inventory requests'
    UNION ALL SELECT 'employees', 'view', 'View employees'
    UNION ALL SELECT 'employees', 'create', 'Create employees and accounts'
    UNION ALL SELECT 'employees', 'edit', 'Edit employees'
    UNION ALL SELECT 'employees', 'delete', 'Delete employees'
    UNION ALL SELECT 'attendance', 'view', 'View attendance'
    UNION ALL SELECT 'attendance', 'create', 'Record attendance'
    UNION ALL SELECT 'attendance', 'edit', 'Edit attendance'
    UNION ALL SELECT 'attendance', 'time_in', 'Record employee time in'
    UNION ALL SELECT 'attendance', 'time_out', 'Record employee time out'
    UNION ALL SELECT 'payroll', 'view', 'View payroll'
    UNION ALL SELECT 'payroll', 'create', 'Create payroll records'
    UNION ALL SELECT 'payroll', 'edit', 'Edit payroll records'
    UNION ALL SELECT 'payroll', 'approve', 'Approve payroll'
    UNION ALL SELECT 'quality_control', 'view', 'View quality control'
    UNION ALL SELECT 'quality_control', 'edit', 'Edit quality control records'
    UNION ALL SELECT 'quality_control', 'approve', 'Approve quality control'
    UNION ALL SELECT 'invoices', 'view', 'View invoices'
    UNION ALL SELECT 'invoices', 'create', 'Create invoices'
    UNION ALL SELECT 'invoices', 'edit', 'Edit invoices'
    UNION ALL SELECT 'payments', 'view', 'View payments'
    UNION ALL SELECT 'payments', 'create', 'Record payments'
    UNION ALL SELECT 'payments', 'edit', 'Edit payments'
    UNION ALL SELECT 'payments', 'approve', 'Approve payments'
    UNION ALL SELECT 'releases', 'view', 'View releases'
    UNION ALL SELECT 'releases', 'create', 'Create releases'
    UNION ALL SELECT 'releases', 'edit', 'Edit releases'
    UNION ALL SELECT 'releases', 'approve', 'Approve releases'
    UNION ALL SELECT 'notifications', 'view', 'View notifications'
    UNION ALL SELECT 'settings', 'view', 'View system settings'
    UNION ALL SELECT 'archive', 'view', 'View archived records'
    UNION ALL SELECT 'archive', 'restore', 'Restore archived records'
    UNION ALL SELECT 'archive', 'delete_permanently', 'Delete archived records permanently'
    UNION ALL SELECT 'audit_logs', 'view', 'View audit logs'
    UNION ALL SELECT 'role_permissions', 'view', 'View roles and permissions'
    UNION ALL SELECT 'role_permissions', 'edit', 'Manage roles and permissions'
) AS catalog
WHERE NOT EXISTS (
    SELECT 1
    FROM permissions existing
    WHERE existing.module = catalog.module
      AND existing.action = catalog.action
);